// <auto-generated />
using System;
using CIS236_Contact_Manager.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CIS236_Contact_Manager.Migrations
{
    [DbContext(typeof(ContactContext))]
    partial class ContactContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CIS236_Contact_Manager.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Family"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Friend"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Work"
                        });
                });

            modelBuilder.Entity("CIS236_Contact_Manager.Models.Contact", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContactId"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Organization")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContactId");

                    b.HasIndex("CategoryID");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            ContactId = 1,
                            CategoryID = 1,
                            DateAdded = new DateTime(2024, 10, 16, 5, 29, 46, 870, DateTimeKind.Utc).AddTicks(2956),
                            EmailAddress = "Adam.First@elo.com",
                            FirstName = "Adam",
                            LastName = "First",
                            Organization = "Sum Org",
                            PhoneNumber = "555-123-3212"
                        },
                        new
                        {
                            ContactId = 2,
                            CategoryID = 1,
                            DateAdded = new DateTime(2024, 10, 15, 5, 29, 46, 870, DateTimeKind.Utc).AddTicks(2968),
                            EmailAddress = "Eve.First@elo.com",
                            FirstName = "Eve",
                            LastName = "First",
                            Organization = "Sum Org",
                            PhoneNumber = "555-321-3212"
                        },
                        new
                        {
                            ContactId = 3,
                            CategoryID = 1,
                            DateAdded = new DateTime(2024, 10, 14, 5, 29, 46, 870, DateTimeKind.Utc).AddTicks(2970),
                            EmailAddress = "Draco.Light@ole.com",
                            FirstName = "Draco",
                            LastName = "Light",
                            Organization = "Top LLC",
                            PhoneNumber = "555-123-3212"
                        });
                });

            modelBuilder.Entity("CIS236_Contact_Manager.Models.Contact", b =>
                {
                    b.HasOne("CIS236_Contact_Manager.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
